name: Demo Workflow
on: 
  push:
    branches:
      - 'main'
jobs:
  print:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps: 
      - name: Print to console
        run: echo Hello GH Actions!
      - name: Print a few lines
        run: |
          echo First line
          echo Second line
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Get repo code
        uses: actions/checkout@v4
      - name: Test application
        run: python hello.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: hello.py
          name: hello-file
  black:
    runs-on: ubuntu-latest
    needs: print
    steps: 
      - name: Get repo code
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4.0.2
        with: 
          path: ~/.cache/pip
          key: 1-pip
      - name: Install black
        run: pip install black
      - name: Test with black
        run: black . --check
  black2:
    runs-on: ubuntu-latest
    needs: print
    steps: 
      - name: Get repo code
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4.0.2
        with: 
          path: ~/.cache/pip
          key: 1-pip
      - name: Install black
        run: pip install black
      - name: Test with black
        run: black . --check
  download:
    needs: print
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-files