name: Demo Workflow
on: 
  push:
    branches:
      - 'main'
jobs:
  print:
    runs-on: ubuntu-latest
    steps: 
      - name: Print to console
        run: echo Hello GH Actions!
      - name: Print a few lines
        run: |
          echo First line
          echo Second line
      - name: Get repo code
        uses: actions/checkout@v4
      - name: Test application
        run: python hello.py
  black:
    runs-on: ubuntu-latest
    needs: print
    steps: 
      - name: Get repo code
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4.0.2
      - name: Install black
        run: pip install black
      - name: Test with black
        run: black . --check
  black2:
    runs-on: ubuntu-latest
    needs: print
    steps: 
      - name: Get repo code
        uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4.0.2
      - name: Install black
        run: pip install black
      - name: Test with black
        run: black . --check
