# name: CI Pipeline

# on:
#   pull_request:
#     branches:
#       - main
#   push:
#     branches:
#       - main

# jobs:
#   lint-and-type-check:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         python-version: ["3.11", "3.10"]

#     outputs:
#       output_1: ${{ steps.gen_output.outputs.output_1 }}
#       output_2: ${{ steps.gen_output.outputs.output_2 }}

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v4
#         with:
#           python-version: ${{ matrix.python-version }}

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install wemake-python-styleguide mypy
#           pip install --upgrade flake8 flake8-quotes flake8-html

#       - name: Run lint and generate HTML report
#         run: |
#           mkdir -p reports
#           flake8 . --format=html --htmldir=reports/lint_report || true

#       - name: Run type check
#         run: python -m mypy .

#       - name: Archive HTML report
#         if: ${{ matrix.python-version == '3.10' }}
#         uses: actions/upload-artifact@v4
#         with:
#           name: lint-report
#           path: reports/lint_report

#       - name: Fail the job if lint errors were found
#         if: ${{ matrix.python-version == '3.10' }}
#         run: |
#           flake8 . || exit 1

#       - name: Set job output
#         id: gen_output
#         if: failure()
#         run: |
#           echo "step_status=failed ${{ matrix.python-version }}" >> $GITHUB_OUTPUT
#           echo "${{ toJSON(github) }}"

#   notify:
#     runs-on: ubuntu-latest
#     needs: lint-and-type-check
#     if: always()

#     steps:
#       - name: Determine status of all jobs
#         run: |
#           message="CI passed on all jobs!"
#           failed_jobs=""
#           echo ${{ toJSON(github) }}
#           echo ${{ toJSON(needs) }}
#           echo ${{ needs.lint-and-type-check.outputs.output_1 }}
#           echo ${{ needs.lint-and-type-check.outputs.output_2 }}

#         #   if [ "${{ needs['lint-and-type-check'].result }}" != "success" ]; then
#         #     for version in 3.11 3.10; do
#         #       if [ "${{ needs['lint-and-type-check'].result }}" != "success" ]; then
#         #         failed_jobs="$failed_jobs Python $version,"
#         #       fi
#         #     done
#         #     message="CI failed on jobs: ${failed_jobs%,}"
#         #   fi

#         #   echo "message=$message" >> $GITHUB_ENV

#     #   - name: Send notification to Telegram
#     #     uses: appleboy/telegram-action@master
#     #     with:
#     #       to: "${{ secrets.TELEGRAM_TO }}"
#     #       token: ${{ secrets.TELEGRAM_TOKEN }}
#     #       message: ${{ env.message }}

# #   notify:
# #     runs-on: ubuntu-latest
# #     needs: [lint, test]
# #     if: always()

# #     steps:
# #         - name: Get message
# #         run: |
# #             if [ "${{ needs.lint.result }}" == "success" ] && [ "${{ needs.test.result }}" == "success" ]; then
# #                 echo "message=CI passed on all jobs!" >> $GITHUB_ENV
# #             else
# #                 echo "message=CI failed!" >> $GITHUB_ENV
# #             fi
# # - name: Send notification to Telegram
# # uses: appleboy/telegram-action@master
# # with:
# #     to: "${{ secrets.TELEGRAM_TO }}"
# #     token: ${{ secrets.TELEGRAM_TOKEN }}
# #     message: ${{ env.message }}

# name: CI Pipeline

# on:
#   pull_request:
#     branches:
#       - main
#   push:
#     branches:
#       - main

# jobs:
#   lint-and-type-check:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         python-version: ["3.11", "3.10"]

#     outputs:
#       output_1: ${{ steps.set_output.outputs.output_1 }}

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v4
#         with:
#           python-version: ${{ matrix.python-version }}

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install wemake-python-styleguide mypy
#           pip install --upgrade flake8 flake8-quotes flake8-html

#       - name: Run lint and generate HTML report
#         run: |
#           mkdir -p reports
#           flake8 . --format=html --htmldir=reports/lint_report || true

#       - name: Run type check
#         run: python -m mypy .

#       - name: Archive HTML report
#         if: matrix.python-version == '3.10'
#         uses: actions/upload-artifact@v4
#         with:
#           name: lint-report
#           path: reports/lint_report

#       - name: Set job output
#         id: set_output
#         run: |
#           echo "output_1=Lint and type check completed for Python ${{ matrix.python-version }}" >> $GITHUB_OUTPUT

#   notify:
#     runs-on: ubuntu-latest
#     needs: lint-and-type-check
#     if: always()

#     steps:
#       - name: Determine status of all jobs
#         run: |
#           message="CI passed on all jobs!"
#           failed_jobs=""

#           # Print the outputs from lint-and-type-check job
#           echo "Output 1: ${{ needs['lint-and-type-check'].outputs.output_1 }}"
#           echo "Message: $message"

# name: CI Pipeline

# on:
#   pull_request:
#     branches:
#       - main
#   push:
#     branches:
#       - main

# jobs:
#   lint-and-type-check:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         python-version: ["3.10", "3.11"]

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v4
#         with:
#           python-version: ${{ matrix.python-version }}

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install wemake-python-styleguide mypy
#           pip install --upgrade flake8 flake8-quotes flake8-html

#       - name: Run lint and generate HTML report
#         run: |
#           mkdir -p reports
#           flake8 . --format=html --htmldir=reports/lint_report || true

#       - name: Run type check
#         run: python -m mypy .

#       - name: Archive HTML report
#         if: matrix.python-version == '3.10'
#         uses: actions/upload-artifact@v4
#         with:
#           name: lint-report
#           path: reports/lint_report

#       - name: Print steps
#         run: echo ${{ toJSON(steps) }}

# name: CI Pipeline

# on:
#   pull_request:
#     branches:
#       - main
#   push:
#     branches:
#       - main

# env:
#   TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}  # Добавьте ваш Telegram Bot API токен в секреты GitHub
#   TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}  # Добавьте ваш Telegram chat ID в секреты GitHub

# jobs:
#   lint-and-type-check:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         python-version: ["3.10", "3.11"]

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Set up Python ${{ matrix.python-version }}
#         uses: actions/setup-python@v4
#         with:
#           python-version: ${{ matrix.python-version }}

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip
#           pip install wemake-python-styleguide mypy
#           pip install --upgrade flake8 flake8-quotes flake8-html

#       - name: Run lint and generate HTML report
#         run: |
#           mkdir -p reports
#           flake8 . --format=html --htmldir=reports/lint_report || true

#       - name: Run type check
#         run: python -m mypy .

#       - name: Fail workflow
#         run: exit 1

#       - name: Archive HTML report
#         if: matrix.python-version == '3.10'
#         uses: actions/upload-artifact@v4
#         with:
#           name: lint-report
#           path: reports/lint_report

#       - name: Capture Failed Step
#         if: failure()
#         id: capture-failure
#         run: |
#           echo ${{ toJSON(steps) }}
#           echo "failed_step=${{ steps.*.name }}" >> $GITHUB_ENV

#   notify:
#     runs-on: ubuntu-latest
#     needs: lint-and-type-check
#     if: always()

#     steps:
#       - name: Determine status and send Telegram notification
#         run: |
#           PROJECT_NAME="${{ github.repository }}"
#           COMMIT_HASH="${{ github.sha }}"
#           STATUS="successfully"
#           FAILED_STEP=""

#           if [ "${{ needs.lint-and-type-check.result }}" != "success" ]; then
#             STATUS="with error"
#             FAILED_STEP=$(echo "Failed on step: ${{ env.failed_step }}")
#           fi

#           MESSAGE="${PROJECT_NAME}: Pipeline for commit ${COMMIT_HASH} finished ${STATUS}! ${FAILED_STEP}"

#           echo ${MESSAGE}

#         #   curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
#         #   -d chat_id="${TELEGRAM_CHAT_ID}" \
#         #   -d text="${MESSAGE}"

name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    outputs:
      failed_step: ${{ steps.capture-failure.outputs.failed_step }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wemake-python-styleguide mypy
          pip install --upgrade flake8 flake8-quotes flake8-html

      - name: Run lint and generate HTML report
        id: run-lint-and-generate-html-report
        run: |
          mkdir -p reports
          flake8 . --format=html --htmldir=reports/lint_report || true

      - name: Run type check
        id: run-type-check
        run: python -m mypy .

      - name: Archive HTML report
        if: matrix.python-version == '3.10'
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: reports/lint_report

      - name: Capture Failed Step
        id: capture-failure
        run: |
          if [ "${{ steps.run-lint-and-generate-html-report.outcome }}" == "failure" ]; then
            echo "failed_step=Run lint and generate HTML report" >> $GITHUB_OUTPUT
          elif [ "${{ steps.run-type-check.outcome }}" == "failure" ]; then
            echo "failed_step=Run type check" >> $GITHUB_OUTPUT
          else
            echo "failed_step=All steps passed" >> $GITHUB_OUTPUT

  notify:
    runs-on: ubuntu-latest
    needs: lint-and-type-check
    if: always()

    steps:
      - name: Send Telegram notification
        run: |
          PROJECT_NAME="${{ github.repository }}"
          COMMIT_HASH="${{ github.sha }}"
          STATUS="successfully"
          FAILED_STEP="${{ needs['lint-and-type-check'].outputs.failed_step }}"

          echo ${{ toJSON(needs) }}

          if [ "$FAILED_STEP" != "All steps passed" ]; then
            STATUS="with error"
            MESSAGE="${PROJECT_NAME}: Pipeline for commit ${COMMIT_HASH} finished ${STATUS}! ${FAILED_STEP} failed."
          else
            MESSAGE="${PROJECT_NAME}: Pipeline for commit ${COMMIT_HASH} finished ${STATUS}!"
          fi

          echo ${MESSAGE}

        #   curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
        #   -d chat_id="${TELEGRAM_CHAT_ID}" \
        #   -d text="${MESSAGE}"
