name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.11', '3.10']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wemake-python-styleguide mypy
        pip install --upgrade flake8 flake8-quotes flake8-html

    - name: Run lint and generate HTML report
      run: |
        mkdir -p reports
        flake8 . --format=html --htmldir=reports/lint_report

    - name: Run type check
      run: python -m mypy .

    - name: Archive HTML report
      if: ${{ matrix.python-version == '3.10' }}
      uses: actions/upload-artifact@v4
      with:
        name: lint-report
        path: reports/lint_report
